#!/usr/bin/env python3
"""Revia AOS traceability matrix generator.

Scans sources for `@satisfies <REQ-ID>` and tests for `@verifies
<REQ-ID>` tags, cross-references them against the requirements in
docs/requirements/AOS-SRS.md, and writes
docs/requirements/trace-matrix.md.

Exit status is non-zero if any requirement lacks implementation or
test coverage, or if any tag references an unknown requirement —
suitable as a CI gate.

Verification-support tool (DO-330 TQL-5 candidate: output is
independently reviewed; the tool cannot insert errors into airborne
software).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRS = ROOT / "docs" / "requirements" / "AOS-SRS.md"
OUT = ROOT / "docs" / "requirements" / "trace-matrix.md"

REQ_RE = re.compile(r"\*\*(AOS-(?:HLR|SRS)-\d{3})\*\*")
TAG_RE = re.compile(r"@(satisfies|verifies)\s+([A-Z0-9-]+(?:\.\.\d+)?)")
ID_RE = re.compile(r"(AOS-(?:HLR|SRS)-)(\d{3})(?:\.\.(\d{3}))?")

SRC_DIRS = ["kernel", "partitions", "config", "tools/host_sim"]
TEST_DIRS = ["tests"]


def expand(tag: str) -> list[str]:
    """Expand 'AOS-SRS-110..115' into the individual IDs."""
    m = ID_RE.fullmatch(tag)
    if not m:
        return [tag]
    prefix, lo, hi = m.group(1), m.group(2), m.group(3)
    if hi is None:
        return [prefix + lo]
    return [f"{prefix}{n:03d}" for n in range(int(lo), int(hi) + 1)]


def scan(dirs: list[str], kind: str) -> dict[str, set[str]]:
    hits: dict[str, set[str]] = {}
    for d in dirs:
        for path in sorted((ROOT / d).rglob("*.[ch]")):
            rel = path.relative_to(ROOT).as_posix()
            for verb, tag in TAG_RE.findall(path.read_text()):
                if verb != kind:
                    continue
                for req in expand(tag):
                    hits.setdefault(req, set()).add(rel)
    return hits


def main() -> int:
    reqs = REQ_RE.findall(SRS.read_text())
    sat = scan(SRC_DIRS, "satisfies")
    ver = scan(TEST_DIRS, "verifies")

    unknown = sorted((set(sat) | set(ver)) - set(reqs))
    rows = []
    missing = []
    for r in reqs:
        impl = ", ".join(sorted(sat.get(r, ()))) or "—"
        test = ", ".join(sorted(ver.get(r, ()))) or "—"
        rows.append(f"| {r} | {impl} | {test} |")
        if r not in sat or r not in ver:
            missing.append(r)

    lines = [
        "# Revia AOS — Traceability Matrix",
        "",
        "GENERATED by tools/trace/gen_trace.py — do not edit.",
        "",
        "| Requirement | Implementation (@satisfies) | Verification (@verifies) |",
        "|---|---|---|",
        *rows,
        "",
        f"Requirements: {len(reqs)} · fully traced: "
        f"{len(reqs) - len(missing)} · gaps: {len(missing)}",
        "",
    ]
    if missing:
        lines.append("## Gaps")
        lines.extend(f"- {r}" for r in missing)
        lines.append("")
    if unknown:
        lines.append("## Tags referencing unknown requirements")
        lines.extend(f"- {r}" for r in unknown)
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(reqs)} requirements, "
          f"{len(missing)} gaps, {len(unknown)} unknown tags")
    return 1 if (missing or unknown) else 0


if __name__ == "__main__":
    sys.exit(main())
